/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Encadrant;
import beans.Etudiant;
import beans.Stage;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.AffectationStageService;
import services.EncadrantService;
import services.EtudiantService;
import services.StageService;

/**
 *
 * @author AMINE
 */
public class AffectationStage extends javax.swing.JInternalFrame {

    private StageService sv;
    private EtudiantService es;
    private EncadrantService ens;
    private AffectationStageService asv;
    private DefaultTableModel model;
    private static int id;

    /**
     * Creates new form AffectationStage
     */
    public AffectationStage() {
        initComponents();
        this.setTitle("Affectation de stage");
        es = new EtudiantService();
        sv = new StageService();
        ens = new EncadrantService();
        asv = new AffectationStageService();
        model = (DefaultTableModel) listeAffectation.getModel();
        loadStage();
        loadEtudiant();
        loadEncadrant();
        load();
    }

    void load() {
        model.setRowCount(0);
        for (beans.AffectationStage as : asv.findAll()) {
            model.addRow(new Object[]{as.getStage().getEntreprise(), as.getEtudiant().getNom() + " " + as.getEtudiant().getPrenom(), as.getEncadrant().getNom() + " " + as.getEncadrant().getPrenom()});
        }

    }

    void loadStage() {
        listeStage.addItem("Choisir une entreprise :");
        for (Stage s : sv.findAll()) {
            listeStage.addItem(s);
        }
    }

    void loadEtudiant() {
        listeEtudiant.addItem("Choisir un etudiant :");
        for (Etudiant e : es.findAll()) {
            listeEtudiant.addItem(e);
        }
    }

    void loadEncadrant() {
        listeEncadrant.addItem("Choisir un encadrant :");
        for (Encadrant e : ens.findAll()) {
            listeEncadrant.addItem(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtStage = new javax.swing.JLabel();
        txtEtudiant = new javax.swing.JLabel();
        txtEncadrant = new javax.swing.JLabel();
        listeStage = new javax.swing.JComboBox();
        listeEtudiant = new javax.swing.JComboBox();
        listeEncadrant = new javax.swing.JComboBox();
        bnAffect = new javax.swing.JButton();
        bnDelete = new javax.swing.JButton();
        bnUpdate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeAffectation = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        txtStage.setText("Stage");

        txtEtudiant.setText("Etudiant");

        txtEncadrant.setText("Encadrant");

        listeStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeStageActionPerformed(evt);
            }
        });

        listeEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeEtudiantActionPerformed(evt);
            }
        });

        listeEncadrant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeEncadrantActionPerformed(evt);
            }
        });

        bnAffect.setBackground(new java.awt.Color(0, 102, 204));
        bnAffect.setIcon(new javax.swing.ImageIcon("E:\\Etude\\S6\\Programmation 3\\projetJava\\Crystal Clear\\22x22\\actions\\edit_add.png")); // NOI18N
        bnAffect.setText("Affecter");
        bnAffect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnAffectActionPerformed(evt);
            }
        });

        bnDelete.setBackground(new java.awt.Color(255, 0, 0));
        bnDelete.setIcon(new javax.swing.ImageIcon("E:\\Etude\\S6\\Programmation 3\\projetJava\\Crystal Clear\\22x22\\actions\\sl_delentry.png")); // NOI18N
        bnDelete.setText("Supprimer");
        bnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnDeleteActionPerformed(evt);
            }
        });

        bnUpdate.setBackground(new java.awt.Color(102, 255, 51));
        bnUpdate.setIcon(new javax.swing.ImageIcon("E:\\Etude\\S6\\Programmation 3\\projetJava\\Crystal Clear\\22x22\\actions\\editcopy.png")); // NOI18N
        bnUpdate.setText("Modifier");
        bnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bnAffect)
                        .addGap(152, 152, 152)
                        .addComponent(bnDelete)
                        .addGap(171, 171, 171)
                        .addComponent(bnUpdate)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStage, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listeStage, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEtudiant)
                            .addComponent(listeEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(150, 150, 150)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEncadrant)
                            .addComponent(listeEncadrant, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStage)
                    .addComponent(txtEtudiant)
                    .addComponent(txtEncadrant))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listeStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listeEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listeEncadrant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnAffect)
                    .addComponent(bnDelete)
                    .addComponent(bnUpdate))
                .addContainerGap())
        );

        listeAffectation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Entreprise", "Etudiant", "Encadrant"
            }
        ));
        listeAffectation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeAffectationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeAffectation);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnAffectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnAffectActionPerformed
        Stage s = (Stage) listeStage.getSelectedItem();
        Etudiant e = (Etudiant) listeEtudiant.getSelectedItem();
        Encadrant en = (Encadrant) listeEncadrant.getSelectedItem();
        if (asv.create(new beans.AffectationStage(s, e, en))) {
            JOptionPane.showMessageDialog(this, "Affectation réussie ");
            load();
        } else {
            JOptionPane.showMessageDialog(this, "Affectation echoué !! ");
        }
    }//GEN-LAST:event_bnAffectActionPerformed

    private void listeStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeStageActionPerformed

    }//GEN-LAST:event_listeStageActionPerformed

    private void listeEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeEtudiantActionPerformed

    }//GEN-LAST:event_listeEtudiantActionPerformed

    private void listeEncadrantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeEncadrantActionPerformed

    }//GEN-LAST:event_listeEncadrantActionPerformed

    private void bnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnDeleteActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer cette affectation ? ");
        if (response == 0) {
            asv.delete((beans.AffectationStage) asv.findAll().get(id));
            load();
        }
    }//GEN-LAST:event_bnDeleteActionPerformed

    private void bnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnUpdateActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Voulez vous modifier les informations de cet étudiant ? ");
        if (response == 0) {
            Stage s = (Stage) listeStage.getSelectedItem();
            Etudiant e = (Etudiant) listeEtudiant.getSelectedItem();
            Encadrant en = (Encadrant) listeEncadrant.getSelectedItem();
            if (asv.update(new beans.AffectationStage(s, e, en))) {
                JOptionPane.showMessageDialog(this, "Bien modifié");
                load();
            } else {
                JOptionPane.showMessageDialog(this, "L'ajout est echoué !");
            }
        }
    }//GEN-LAST:event_bnUpdateActionPerformed

    private void listeAffectationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeAffectationMouseClicked
        
        listeStage.setSelectedItem(model.getValueAt(listeAffectation.getSelectedRow(), 0));
        listeEtudiant.setSelectedItem(model.getValueAt(listeAffectation.getSelectedRow(), 1).toString());
        listeEncadrant.setSelectedItem(model.getValueAt(listeAffectation.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_listeAffectationMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnAffect;
    private javax.swing.JButton bnDelete;
    private javax.swing.JButton bnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listeAffectation;
    private javax.swing.JComboBox listeEncadrant;
    private javax.swing.JComboBox listeEtudiant;
    private javax.swing.JComboBox listeStage;
    private javax.swing.JLabel txtEncadrant;
    private javax.swing.JLabel txtEtudiant;
    private javax.swing.JLabel txtStage;
    // End of variables declaration//GEN-END:variables
}
