/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;

/**
 *
 * @author AMINE
 */
public class MDIApplication extends javax.swing.JFrame {
    private static MDIApplication instance;
    /**
     * Creates new form MDIApplication
     */
    public MDIApplication() {
        initComponents();
        this.setTitle("Gestion des stages");
        this.setExtendedState(MAXIMIZED_BOTH);
        //
         // Crée le DesktopPane pour gérer les sous-fenêtres
        desktopPane = new JDesktopPane();
        setContentPane(desktopPane);

        // Ajoute le graphique (Barchart) en tant que JInternalFrame
        openBarChartInternalFrame();
       
    }
    private void openBarChartInternalFrame() {
        // Crée et affiche le graphique dans un JInternalFrame
        Barchart barchartFrame = new Barchart();  // Assurez-vous que Barchart est un JInternalFrame
        barchartFrame.setVisible(true);           // Affiche le graphique
    }
    
    
    
    public static MDIApplication getInstance() {
        if (instance == null) {
            instance = new MDIApplication();
        }
        return instance;
    }
    
    private void fermerFenetresExistantes(JDesktopPane desktop) {
    for (JInternalFrame frame : desktop.getAllFrames()) {
        frame.dispose(); 
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        etudiantMenuItem = new javax.swing.JMenuItem();
        encadrantMenuItem = new javax.swing.JMenuItem();
        stageMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        EtudiantByStage = new javax.swing.JMenuItem();
        affectationStage = new javax.swing.JMenuItem();
        StageBySujet = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        etudiantMenuItem.setMnemonic('o');
        etudiantMenuItem.setText("Etudiant");
        etudiantMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etudiantMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(etudiantMenuItem);

        encadrantMenuItem.setMnemonic('s');
        encadrantMenuItem.setText("Encadrant");
        encadrantMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encadrantMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(encadrantMenuItem);

        stageMenuItem.setMnemonic('a');
        stageMenuItem.setText("Stage");
        stageMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stageMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(stageMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Fonctionnalités");

        EtudiantByStage.setMnemonic('t');
        EtudiantByStage.setText("Filtrer les stages par entreprise");
        EtudiantByStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EtudiantByStageActionPerformed(evt);
            }
        });
        editMenu.add(EtudiantByStage);

        affectationStage.setText("Affectation Stage");
        affectationStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affectationStageActionPerformed(evt);
            }
        });
        editMenu.add(affectationStage);

        StageBySujet.setText("Rechercher stage par sujet");
        StageBySujet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StageBySujetActionPerformed(evt);
            }
        });
        editMenu.add(StageBySujet);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Statistiques");
        helpMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMenuMouseClicked(evt);
            }
        });
        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encadrantMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encadrantMenuItemActionPerformed
        fermerFenetresExistantes(desktopPane);
        EncadrantForm enf = new EncadrantForm();
        desktopPane.add(enf);
        enf.setVisible(true);
    }//GEN-LAST:event_encadrantMenuItemActionPerformed

    private void etudiantMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etudiantMenuItemActionPerformed
        fermerFenetresExistantes(desktopPane);
        EtudiantForm ef = new EtudiantForm();
        desktopPane.add(ef);
        ef.setVisible(true);
    }//GEN-LAST:event_etudiantMenuItemActionPerformed

    private void stageMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stageMenuItemActionPerformed
        fermerFenetresExistantes(desktopPane);
        StageForm sf = new StageForm();
        desktopPane.add(sf);
        sf.setVisible(true);
    }//GEN-LAST:event_stageMenuItemActionPerformed

    private void EtudiantByStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EtudiantByStageActionPerformed
        fermerFenetresExistantes(desktopPane);
        EtudiantByStage ebs = new EtudiantByStage();
        desktopPane.add(ebs);
        ebs.setVisible(true);
    }//GEN-LAST:event_EtudiantByStageActionPerformed

    private void affectationStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affectationStageActionPerformed
        fermerFenetresExistantes(desktopPane);
        AffectationStage as = new AffectationStage();
        desktopPane.add(as);
        as.setVisible(true);
    }//GEN-LAST:event_affectationStageActionPerformed

    private void StageBySujetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StageBySujetActionPerformed
       fermerFenetresExistantes(desktopPane);
       StageBySujet sbs = new StageBySujet();
       desktopPane.add(sbs);
       sbs.setVisible(true);
    }//GEN-LAST:event_StageBySujetActionPerformed

    private void helpMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMenuMouseClicked
        fermerFenetresExistantes(desktopPane);
        Barchart bs = new Barchart();
        desktopPane.add(bs);
        bs.setVisible(true);
    }//GEN-LAST:event_helpMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EtudiantByStage;
    private javax.swing.JMenuItem StageBySujet;
    private javax.swing.JMenuItem affectationStage;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem encadrantMenuItem;
    private javax.swing.JMenuItem etudiantMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem stageMenuItem;
    // End of variables declaration//GEN-END:variables

}
